modules:
  blazemeter:
    token: 0cf14f706008495f716a1268:831ff16a2e4ee4a0a4c911706ce109f00ef44d5d8d9910824eb1321a3d3e9df10cfcbd80

execution:
- executor: robot
  concurrency: 50
  hold-for: 2m
  ramp-up: 10s
  scenario: bob

- executor: robot
  concurrency: 50
  hold-for: 2m
  ramp-up: 10s
  scenario: dave

scenarios:
  bob:
    variables:
      XRS_HOST_ENVIRONMENT: d3
      XRS_TEST_BENCH_FOLDER_NAME: KSTINE2_D3_TestBench
    tags: xrsawsperftest
    script: /automation.product.api.xrs.webservice.test/Tests/AWS_XRS_WebServicesTests/01__EntityManagementTestSuites/01__ValidateAWSXRSDeviceWebServices.robot
  dave:
    variables:
      XRS_HOST_ENVIRONMENT: d3
      XRS_TEST_BENCH_FOLDER_NAME: KSTINE2_D3_TestBench
    tags: xrsperftest
    script: /automation.product.api.xrs.webservice.test/Tests/XRS_WebServicesTests/01__EntityManagementTestSuites/01__ValidateXRSDeviceWebServices.robot

reporting:
  - module: blazemeter
    report-name: XRS Performance Test
    test: AWS XRS Web Services Get Tests
    project: XRS Web Services